CREATE TABLE BLOOD_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    BLOOD_GROUP VARCHAR2(5),
    QUANTITY NUMBER,
    REQUEST_DATE DATE,
    STATUS VARCHAR2(20)
);

INSERT INTO BLOOD_REQUEST VALUES (201,'A+',2,'05-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (202,'B+',1,'06-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (203,'O+',3,'07-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (204,'A-',1,'08-OCT-25','Pending');