CREATE TABLE BLOOD_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    BLOOD_GROUP VARCHAR2(5),
    QUANTITY NUMBER,
    REQUEST_DATE DATE,
    STATUS VARCHAR2(20)
);

INSERT INTO BLOOD_REQUEST VALUES (201,'A+',2,'05-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (202,'B+',1,'06-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (203,'O+',3,'07-OCT-25','Approved');
INSERT INTO BLOOD_REQUEST VALUES (204,'A-',1,'08-OCT-25','Pending');

SELECT *FROM BLOOD_REQUEST WHERE STATUS IN ('Pending');
SELECT *FROM BLOOD_REQUEST WHERE STATUS IN ('Approved','Pending');
SELECT *FROM BLOOD_REQUEST ORDER BY Quantity DESC;

UPDATE BLOOD_REQUEST SET STATUS='Approved' WHERE REQUEST_ID = 202;
DELETE FROM BLOOD_REQUEST WHERE STATUS = 'Rejected';
SELECT MIN(QUANTITY) FROM BLOOD_REQUEST;
TRUNCATE TABLE BLOOD_REQUEST;